# Generated by Django 6.0 on 2026-01-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='заголовок', max_length=1000, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, help_text='Сообщение', null=True, verbose_name='Ваша заметка')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='image/product/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('views_counter', models.PositiveIntegerField(default=0, help_text='Укажите количество просмотров', verbose_name='Счетчик просмотров')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['name'],
            },
        ),
    ]
