# Generated by Django 4.2.2 on 2026-02-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_category_id_alter_contact_id_alter_product_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'name'], 'permissions': [('can_unpublish_product', 'Can unpublish product')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован')], default='draft', max_length=30),
        ),
    ]
